version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: ocp-planning-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ocp_planning_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ocp-planning-network

volumes:
  mysql_data:

networks:
  ocp-planning-network:
    driver: bridge