spring:
  application:
    name: ${APP_NAME:backend}  # Use environment variable APP_NAME if available, otherwise default to 'backend'
  datasource:
    driver-class-name: ${DB_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}  # Default to the given value
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:fahd_pln_db}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:marouane}  # Default to the given value
    password: ${DB_PASSWORD:Marouane@2001}  # Default to the given value
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:update}  # Default to 'update'
    database: ${JPA_DATABASE:mysql}  # Default to 'mysql'
    database-platform: ${JPA_DATABASE_PLATFORM:org.hibernate.dialect.MySQLDialect}  # Default to the given value

server:
  port: ${SERVER_PORT:8082}  # Default to 8082


cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}  # Default to the given value
  
logging:
  level:
    org.springframework: DEBUG
    hibernate: DEBUG
    security: DEBUG
    com.idirtrack: DEBUG
