server:
  port: 8082

spring:
  application:
    name: ocp-planning-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ocp_planning_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

cors:
  allowed-origins: http://localhost:3000
  
logging:
  level:
    org.springframework: DEBUG
    hibernate: DEBUG
    security: DEBUG
